const API_URL='https://script.google.com/macros/s/AKfycbxIH2VtgwRi50xduXgrkYrjD0yrzNfQ5vCWt1XgOzil6LZSgXNj6MJo9jPYvOkjNHdu/exec';
const $=id=>document.getElementById(id);
let students=[],selected=new Map(),activeGrades=new Set(['中１','中２','中３']);
const INITIAL_EXAM_NUMBERS={"1058":"2001","1097":"1001","1100":"1002","1117":"1003","1139":"1004","1154":"1005","1164":"1006","1169":"2002","1181":"1007","1188":"1008","1191":"1009","1202":"3001","1214":"3002","1219":"3003","1226":"2003","1227":"3004","1237":"3005","1239":"1010","1248":"2004","1249":"2005","1252":"2006","1253":"2007","1257":"3006","1259":"3007","1263":"2008","1264":"2009","1269":"2010","1276":"3008","1282":"2011","1286":"3009","1287":"3010","1289":"2012","1290":"3011","1293":"2013","1294":"2014","1295":"3012","1296":"2015","1297":"1011","1298":"2016","1299":"2017","1302":"2018","1303":"2019","1304":"2020","1305":"3013","1306":"2021","1307":"2022","1311":"1012","1312":"3014","1313":"1013","1316":"2023","1318":"2024","1319":"2025","1320":"2026","1321":"1014","1322":"1015","1324":"2027","1325":"3015","1326":"2028","1327":"3016","1328":"2029","1329":"2030","1330":"1016"};

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(value){return String(value??'').normalize('NFKC').toLowerCase().replace(/[\s　]+/g,'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb=`exam_cb_${Date.now()}_${Math.random().toString(36).slice(2)}`;const script=document.createElement('script');const timer=setTimeout(()=>finish(new Error('通信がタイムアウトしました。')),45000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove();}function finish(error,data){cleanup();error?reject(error):resolve(data);}window[cb]=data=>data?.error?finish(new Error(data.message||'読み込みに失敗しました。')):finish(null,data);script.onerror=()=>finish(new Error('生徒情報を読み込めませんでした。'));script.src=`${API_URL}?${new URLSearchParams({action,callback:cb,...params})}`;document.body.appendChild(script);});}
function setStatus(message,type=''){const el=$('status');el.textContent=message;el.className=`status ${type}`.trim();}
function filtered(){const campus=$('campusFilter').value,q=normalize($('searchInput').value);return students.filter(s=>(campus==='all'||s.campus===campus)&&activeGrades.has(s.grade)&&(!q||[s.studentId,s.name,s.kana].map(normalize).some(v=>v.includes(q)))).sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));}
function renderGradeButtons(){$('gradeButtons').innerHTML=['中１','中２','中３'].map(g=>`<button type="button" class="gradeBtn ${activeGrades.has(g)?'active':''}" data-grade="${g}">${g}</button>`).join('');document.querySelectorAll('.gradeBtn').forEach(btn=>btn.onclick=()=>{activeGrades.has(btn.dataset.grade)?activeGrades.delete(btn.dataset.grade):activeGrades.add(btn.dataset.grade);renderGradeButtons();renderStudents();});}
function renderStudents(){const list=filtered();$('listCount').textContent=`${list.length}人表示 / ${students.length}人在籍`;$('studentList').innerHTML=list.map(s=>`<label class="studentRow ${selected.has(s.studentId)?'selected':''}" data-id="${escapeHtml(s.studentId)}"><input type="checkbox" ${selected.has(s.studentId)?'checked':''}><span class="examNo">${escapeHtml(s.examNumber)}</span><strong>${escapeHtml(s.name)}</strong><span class="gradeBadge">${escapeHtml(s.grade)}</span><span class="campus">${escapeHtml(s.campus)}校</span><span class="campus">ID ${escapeHtml(s.studentId)}</span></label>`).join('')||'<div class="muted" style="padding:18px">該当する生徒はいません。</div>';document.querySelectorAll('.studentRow').forEach(row=>row.onclick=e=>{e.preventDefault();toggleStudent(row.dataset.id);});renderSelected();}
function toggleStudent(id){const s=students.find(x=>x.studentId===id);if(!s)return;selected.has(id)?selected.delete(id):selected.set(id,s);renderStudents();}
function renderSelected(){const list=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));$('selectedCount').textContent=`${list.length}人`;$('selectedList').innerHTML=list.length?list.map(s=>`<span class="selectedChip"><b>${escapeHtml(s.examNumber)}</b> ${escapeHtml(s.name)}<button type="button" data-remove="${escapeHtml(s.studentId)}" aria-label="${escapeHtml(s.name)}を解除">×</button></span>`).join(''):'<span class="muted">まだ選択されていません。</span>';$('selectedList').querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{selected.delete(btn.dataset.remove);renderStudents();});$('printBtn').disabled=!list.length;renderPreview();}
function campusName(s){return s?.campus==='大手'?'大手町校':s?.campus==='神領'?'神領校':String(s?.campus||'');}
function ticketMarkup(s,print=false){const round=$('roundSelect').value;const footer=`個別指導ステップ ${campusName(s)}`.trim();return `<div class="${print?'printPage':''}"><div class="ticketTitle">第${escapeHtml(round)}回 愛知全県模試受験票</div><div class="ticketTable"><div class="ticketLabel">塾名</div><div class="ticketValue">個別指導ステップ</div><div class="ticketLabel">塾コード</div><div class="ticketValue number">4258</div><div class="ticketLabel">生徒コード</div><div class="ticketValue number">${escapeHtml(s?.examNumber||'----')}</div><div class="ticketLabel">氏名</div><div class="ticketValue">${escapeHtml(s?.name||'選択した生徒の氏名')}</div><div class="ticketLabel">学区</div><div class="ticketValue">尾張</div></div><div class="${print?'printFooter':'previewFooter'}">${escapeHtml(footer)}</div></div>`;}
function renderPreview(){const first=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber))[0];$('ticketPreview').innerHTML=ticketMarkup(first,false)+(first?'':`<p class="previewHint">生徒を選択すると氏名と受験番号が入ります。</p>`);}
function fallbackStudent_(s){const id=String(s.id||'');const grade=String(s.grade||'').replace('中1','中１').replace('中2','中２').replace('中3','中３');const school=String(s.school||'');return {studentId:id,name:String(s.name||''),kana:String(s.kana||s.furigana||''),grade,campus:school.includes('神領')?'神領':school.includes('大手')?'大手':school,examNumber:INITIAL_EXAM_NUMBERS[id]};}
async function loadStudents(refresh=false){setStatus(refresh?'生徒情報と受験番号を更新しています…':'生徒情報を読み込んでいます…');try{let data=await jsonp('getExamTicketStudents',{refresh:refresh?'1':'0',_:Date.now()});let fallback=false;if(!Array.isArray(data?.students)){const base=await jsonp('getStudents',{_:Date.now()});data={students:(Array.isArray(base)?base:[]).filter(s=>INITIAL_EXAM_NUMBERS[String(s.id||'')]).map(fallbackStudent_),warnings:[]};fallback=true;}students=data.students;const valid=new Set(students.map(s=>s.studentId));for(const id of selected.keys())if(!valid.has(id))selected.delete(id);renderStudents();const warning=(data.warnings||[]).join(' / ');setStatus(`${students.length}名を読み込みました。受験番号は保存済みです。${fallback?'（初期登録済み番号を使用）':''}${warning?'　注意：'+warning:''}`,warning?'error':'ok');}catch(e){setStatus(e.message,'error');}}
function printTickets(){if(!selected.size)return;const list=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));$('printArea').innerHTML=list.map(s=>ticketMarkup(s,true)).join('');window.print();}

$('campusFilter').onchange=renderStudents;$('searchInput').oninput=renderStudents;$('roundSelect').onchange=renderPreview;$('selectVisibleBtn').onclick=()=>{filtered().forEach(s=>selected.set(s.studentId,s));renderStudents();};$('clearBtn').onclick=()=>{selected.clear();renderStudents();};$('refreshBtn').onclick=()=>loadStudents(true);$('printBtn').onclick=printTickets;window.addEventListener('afterprint',()=>{$('printArea').innerHTML='';});renderGradeButtons();renderPreview();loadStudents();
