const API_URL='https://script.google.com/macros/s/AKfycbxIH2VtgwRi50xduXgrkYrjD0yrzNfQ5vCWt1XgOzil6LZSgXNj6MJo9jPYvOkjNHdu/exec';
const $=id=>document.getElementById(id);
let students=[],selected=new Map(),activeGrades=new Set(['中１','中２','中３']);

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(value){return String(value??'').normalize('NFKC').toLowerCase().replace(/[\s　]+/g,'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb=`exam_cb_${Date.now()}_${Math.random().toString(36).slice(2)}`;const script=document.createElement('script');const timer=setTimeout(()=>finish(new Error('通信がタイムアウトしました。')),45000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove();}function finish(error,data){cleanup();error?reject(error):resolve(data);}window[cb]=data=>data?.error?finish(new Error(data.message||'読み込みに失敗しました。')):finish(null,data);script.onerror=()=>finish(new Error('生徒情報を読み込めませんでした。'));script.src=`${API_URL}?${new URLSearchParams({action,callback:cb,...params})}`;document.body.appendChild(script);});}
function setStatus(message,type=''){const el=$('status');el.textContent=message;el.className=`status ${type}`.trim();}
function filtered(){const campus=$('campusFilter').value,q=normalize($('searchInput').value);return students.filter(s=>(campus==='all'||s.campus===campus)&&activeGrades.has(s.grade)&&(!q||[s.studentId,s.name,s.kana].map(normalize).some(v=>v.includes(q)))).sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));}
function renderGradeButtons(){$('gradeButtons').innerHTML=['中１','中２','中３'].map(g=>`<button type="button" class="gradeBtn ${activeGrades.has(g)?'active':''}" data-grade="${g}">${g}</button>`).join('');document.querySelectorAll('.gradeBtn').forEach(btn=>btn.onclick=()=>{activeGrades.has(btn.dataset.grade)?activeGrades.delete(btn.dataset.grade):activeGrades.add(btn.dataset.grade);renderGradeButtons();renderStudents();});}
function renderStudents(){const list=filtered();$('listCount').textContent=`${list.length}人表示 / ${students.length}人在籍`;$('studentList').innerHTML=list.map(s=>`<label class="studentRow ${selected.has(s.studentId)?'selected':''}" data-id="${escapeHtml(s.studentId)}"><input type="checkbox" ${selected.has(s.studentId)?'checked':''}><span class="examNo">${escapeHtml(s.examNumber)}</span><strong>${escapeHtml(s.name)}</strong><span class="gradeBadge">${escapeHtml(s.grade)}</span><span class="campus">${escapeHtml(s.campus)}校</span><span class="campus">ID ${escapeHtml(s.studentId)}</span></label>`).join('')||'<div class="muted" style="padding:18px">該当する生徒はいません。</div>';document.querySelectorAll('.studentRow').forEach(row=>row.onclick=e=>{e.preventDefault();toggleStudent(row.dataset.id);});renderSelected();}
function toggleStudent(id){const s=students.find(x=>x.studentId===id);if(!s)return;selected.has(id)?selected.delete(id):selected.set(id,s);renderStudents();}
function renderSelected(){const list=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));$('selectedCount').textContent=`${list.length}人`;$('selectedList').innerHTML=list.length?list.map(s=>`<span class="selectedChip"><b>${escapeHtml(s.examNumber)}</b> ${escapeHtml(s.name)}<button type="button" data-remove="${escapeHtml(s.studentId)}" aria-label="${escapeHtml(s.name)}を解除">×</button></span>`).join(''):'<span class="muted">まだ選択されていません。</span>';$('selectedList').querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{selected.delete(btn.dataset.remove);renderStudents();});$('printBtn').disabled=!list.length;renderPreview();}
function ticketMarkup(s,print=false){const round=$('roundSelect').value;return `<div class="${print?'printPage':''}"><div class="ticketTitle">第${escapeHtml(round)}回 愛知全県模試受験票</div><div class="ticketTable"><div class="ticketLabel">塾名</div><div class="ticketValue">個別指導ステップ</div><div class="ticketLabel">塾コード</div><div class="ticketValue number">4258</div><div class="ticketLabel">生徒コード</div><div class="ticketValue number">${escapeHtml(s?.examNumber||'----')}</div><div class="ticketLabel">氏名</div><div class="ticketValue">${escapeHtml(s?.name||'選択した生徒の氏名')}</div><div class="ticketLabel">学区</div><div class="ticketValue">尾張</div></div>${print?'<div class="printFooter">個別指導ステップ</div>':''}</div>`;}
function renderPreview(){const first=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber))[0];$('ticketPreview').innerHTML=ticketMarkup(first,false)+(first?'':`<p class="previewHint">生徒を選択すると氏名と受験番号が入ります。</p>`);}
async function loadStudents(refresh=false){setStatus(refresh?'生徒情報と受験番号を更新しています…':'生徒情報を読み込んでいます…');try{const data=await jsonp('getExamTicketStudents',{refresh:refresh?'1':'0',_:Date.now()});students=Array.isArray(data?.students)?data.students:[];const valid=new Set(students.map(s=>s.studentId));for(const id of selected.keys())if(!valid.has(id))selected.delete(id);renderStudents();const warning=(data.warnings||[]).join(' / ');setStatus(`${students.length}名を読み込みました。受験番号は保存済みです。${warning?'　注意：'+warning:''}`,warning?'error':'ok');}catch(e){setStatus(e.message,'error');}}
function printTickets(){if(!selected.size)return;const list=[...selected.values()].sort((a,b)=>Number(a.examNumber)-Number(b.examNumber));$('printArea').innerHTML=list.map(s=>ticketMarkup(s,true)).join('');window.print();}

$('campusFilter').onchange=renderStudents;$('searchInput').oninput=renderStudents;$('roundSelect').onchange=renderPreview;$('selectVisibleBtn').onclick=()=>{filtered().forEach(s=>selected.set(s.studentId,s));renderStudents();};$('clearBtn').onclick=()=>{selected.clear();renderStudents();};$('refreshBtn').onclick=()=>loadStudents(true);$('printBtn').onclick=printTickets;window.addEventListener('afterprint',()=>{$('printArea').innerHTML='';});renderGradeButtons();renderPreview();loadStudents();
