let templates=[], current=null; const $=id=>document.getElementById(id);
async function load(){templates=await api.getTemplates(); renderSelect(); loadHistory()}
function renderSelect(){ $('templateSelect').innerHTML='<option value="">新規作成</option>'+templates.map(t=>`<option value="${t.id}">${t.name}</option>`).join('') }
function show(t){current=t; $('nameInput').value=t?.name||''; $('subjectInput').value=t?.subject||''; $('bodyInput').value=t?.body||''; $('templateSelect').value=t?.id||'' }
async function save(asNew){const payload={id:current?.id||'',name:$('nameInput').value,subject:$('subjectInput').value,body:$('bodyInput').value}; if(!payload.name||!payload.subject){alert('タイトルと件名を入力してください');return} const res=asNew?await api.saveTemplateAs(payload):await api.saveTemplate(payload); $('status').textContent='保存しました'; templates=await api.getTemplates(); renderSelect(); show(templates.find(t=>t.id===res.id));}
async function del(){if(!current){alert('削除するテンプレートを選択してください');return} if(!confirm('削除しますか？'))return; await api.deleteTemplate(current.id); $('status').textContent='削除しました'; templates=await api.getTemplates(); renderSelect(); show(null)}
function insert(text){const ta=$('bodyInput'); const st=ta.selectionStart, en=ta.selectionEnd; ta.value=ta.value.slice(0,st)+text+ta.value.slice(en); ta.focus(); ta.selectionStart=ta.selectionEnd=st+text.length}
async function loadHistory(){const data=await api.getHistory({q:$('historySearch').value});$('historyList').innerHTML=data.map(h=>`<div class="historyItem"><div class="historyMeta">${h.sentDateLabel}</div><div class="historyTitle">${h.titleLine}</div><div class="historyMeta">${h.targetLine}</div><details class="details"><summary>本文を表示</summary><pre>${h.body||''}</pre></details></div>`).join('')||'<div class="muted">履歴がありません。</div>'}
document.addEventListener('DOMContentLoaded',()=>{load(); $('templateSelect').onchange=()=>show(templates.find(t=>t.id===$('templateSelect').value)||null); $('newBtn').onclick=()=>show(null); $('saveBtn').onclick=()=>save(false); $('saveAsBtn').onclick=()=>save(true); $('deleteBtn').onclick=del; document.querySelectorAll('[data-ins]').forEach(b=>b.onclick=()=>insert(b.dataset.ins)); $('reloadHistory').onclick=loadHistory; $('historySearch').oninput=loadHistory;});
